---
ntp_server: 216.239.35.0
dns_server: 8.8.8.8

interfaces:
  - name: Ethernet1/1
    description: WAN_UPLINK
    ip: 203.0.113.1
    mask: 255.255.255.252
    shutdown: false
  - name: Ethernet1/2
    description: LAN_SEGMENT
    ip: 10.0.0.1
    mask: 255.255.255.0
    shutdown: false
